version: "3.8"

volumes:
  grafana_data:
  prometheus_data:

networks:
  monitoring:
    external: true

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
      - 3000:3000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=360h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  snmp:
    image: quay.io/prometheus/snmp-exporter
    container_name: snmp-exporter
    volumes:
      - /opt/docker-persist/snmp-exporter:/etc/snmp_exporter
    ports:
      - 9116:9116
      - 116:116/udp
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml
    networks:
      - monitoring
